apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: matrix-appset-backend-app
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - appName: single-helm
                - appName: double-helm
          - list:
              elements:
                - name: matrix-helm1-resource
                  valuesPath: "Generator-resources/matrix-appset-resource/matrix-helm1-resource"
                - name: matrix-helm2-resource
                  valuesPath: "Generator-resources/matrix-appset-resource/matrix-helm2-appset-resource"
                
  template:
    metadata:
      name: '{{appName}}-{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/NaveenBalagouni/argocd-training.git"
        targetRevision: "HEAD"
        path: "{{valuesPath}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: naveen-appset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
