apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-source-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NaveenBalagouni/argocd-training
    targetRevision: HEAD
    path: path/to/directory1
    path: path/to/directory1
    # Specify multiple sources here
    directory:
      recurse: true
  destinations:
  - server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

