apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
    path: 'two -git-sources/two-git'
    targetRevision: HEAD
    repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
    path: 'two -git-sources/git-sources'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: two-sources
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
