replicaCount: 1

image:
  repository: naveenbalagouni/python-docker-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80


ingress:
  enabled: false
  host: ""
  path: /

environment: default

