apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-generator
spec:
  generators:
  - git:
      repoURL: https://github.com/NaveenBalagouni/argocd-training.git
      revision: "HEAD"
      directories:
      - path: 'Generator-resources/git-appset-resources/appset-git3/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/NaveenBalagouni/argocd-training.git
        targetRevision: "HEAD"
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: naveen-appset

