apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-generator
spec:
  generators:
  - git:
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      directories:
      - path: 'guestbook/*'
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

