apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app  # Match the app label to route traffic to the deployment
  ports:
    - protocol: TCP
      port: 80           # External port to expose
      targetPort: 80      # Internal container port
  # No type specified, defaults to ClusterIP
