apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: list-applicationset-first-application
            repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
            targetRevision: 'HEAD'
            path: Generator-resources/list-resources/list1 

          - name: list-applicationset-second-application
            repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
            targetRevision: 'HEAD'
            path: Generator-resources/list-resources/list2
  
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://dev-vcluster.opencd.opsmx.org:443
        namespace: '{{name}}-namespace'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
