apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: list-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: naveen-list-appsetfirst-application
            repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
            targetRevision: 'HEAD'
            path: Generator-resources/list-resources/list

          - name: naveen-list-appsetsecond-application
            repoURL: 'https://github.com/NaveenBalagouni/argocd-training.git'
            targetRevision: 'HEAD'
            path: Generator-resources/list-resources/list2
  
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: naveen-appset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
