replicaCount: 1

image:
  repository: naveenbalagouni/my-web-app     # ✅ Public image from Docker Hub
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080


ingress:
  enabled: false
  host: ""
  path: /


